import { stageLabel } from "./stage";

/* Afya's built-in knowledge, used when the live AI isn't available.
   Short, evidence-based answers (ACOG, CDC, NIH, USDA). Each topic lists trigger words; the best match wins. */

const T = (id, keys, text, extra = {}) => ({ id, keys, text, ...extra });

export const TOPICS = [
  T("heartburn", ["heartburn", "acid", "reflux", "indigestion", "burning chest"], "Heartburn is really common as your baby grows. Smaller meals, sitting upright for an hour after eating, and an earlier, lighter dinner all help. Spicy, fried and very acidic foods (tomato stews, citrus) are frequent triggers, so notice which ones bother you rather than cutting everything.", { foods: ["greek-yogurt", "plantain"], note: "If heartburn comes with pain under your ribs on the right, a bad headache or vision changes, call your provider today.", questions: ["My heartburn is bothering me. What's safe to take for it?"] }),
  T("constipation", ["constipat", "can't poop", "cant poop", "bloat", "gas", "hard stool"], "Constipation is so common in pregnancy, partly from hormones and partly from iron in prenatal vitamins. Fiber and fluids are your best friends: beans, lentils, okra, greens, oats, fruit like papaya or prunes, and plenty of water. A short walk after meals helps too.", { foods: ["black-eyed-peas", "okra", "lentils"], nutrients: ["Fiber"] }),
  T("cravings", ["crav", "want to eat", "craving"], "Cravings are normal, and it's fine to enjoy them. A trick that helps: pair the craving with something nourishing, like ice cream with fruit, or chips with beans and avocado. If you crave things that aren't food (ice, clay, chalk, starch), tell your provider, because that can be a sign of low iron.", { nutrients: ["Iron"] }),
  T("pica", ["clay", "chalk", "eat ice", "chewing ice", "dirt", "laundry starch", "eko", "kaolin"], "Craving non-food things like clay, chalk, ice or laundry starch is called pica. It's more common than people think, and you're not alone. Please mention it to your provider, since it's sometimes linked to low iron, and some clays can carry lead.", { questions: ["I've been craving clay/ice. Should we check my iron?"] }),
  T("caffeine", ["caffeine", "coffee", "tea", "soda", "energy drink", "cola"], "Up to 200 mg of caffeine a day is considered okay in pregnancy. That's about one 12-oz cup of brewed coffee. Remember tea, cola and chocolate count too, and energy drinks are best skipped."),
  T("alcohol", ["alcohol", "wine", "beer", "a drink", "liquor", "palm wine", "drunk", "cocktail"], "There's no known safe amount of alcohol in pregnancy, so the advice is none at all. While breastfeeding, an occasional drink is generally okay if you wait at least 2 hours per drink before nursing. If cutting back is hard, your provider can help without judgment."),
  T("fish", ["fish", "tuna", "mercury", "seafood", "shrimp", "salmon", "sardine", "tilapia", "mackerel"], "Fish is great in pregnancy: aim for 2 to 3 servings a week of low-mercury choices like salmon, sardines, tilapia, catfish, shrimp and canned light tuna. Skip high-mercury fish: shark, swordfish, king mackerel, bigeye tuna and tilefish. Cook it until it flakes.", { foods: ["salmon"], nutrients: ["Omega-3", "Protein"] }),
  T("deli", ["deli", "lunch meat", "hot dog", "cold cuts", "listeria", "smoked"], "Deli meats, hot dogs and refrigerated smoked fish can carry listeria, which is riskier in pregnancy. They're fine if heated until steaming hot (165°F). Shelf-stable canned versions are okay too."),
  T("eggs", ["egg", "eggs", "runny", "raw egg", "mayo"], "Eggs are a pregnancy superfood: protein plus choline for your baby's brain. Just cook them until the yolk is firm, and skip raw egg in things like homemade mayo or cookie dough.", { nutrients: ["Choline", "Protein"] }),
  T("meat", ["undercooked", "rare", "medium rare", "steak", "suya", "pink"], "Cook meat all the way through in pregnancy: beef and lamb to 160°F if ground (145°F for whole cuts with a rest), poultry to 165°F. It protects you from toxoplasmosis and other infections. Suya and grilled meats are great when cooked through."),
  T("dairy", ["milk", "cheese", "dairy", "lactose", "calcium", "yogurt"], "You need about 1,000 mg of calcium a day. Pasteurized milk, yogurt and hard cheeses are easy sources. If dairy doesn't agree with you, try calcium-fortified plant milk, canned sardines with bones, collards, callaloo or fortified juice. Avoid unpasteurized milk and soft cheeses made from it.", { foods: ["greek-yogurt", "collards", "callaloo"], nutrients: ["Calcium"] }),
  T("folate", ["folate", "folic"], "Folate helps build your baby's brain and spine. You need about 600 mcg a day in pregnancy. Beans, lentils, black-eyed peas, leafy greens, avocado and fortified grains are great sources, and most prenatal vitamins include folic acid.", { foods: ["lentils", "black-eyed-peas", "avocado"], nutrients: ["Folate"] }),
  T("protein", ["protein", "vegetarian", "vegan", "plant based", "no meat"], "You need about 71 g of protein a day in pregnancy. Beans, lentils, peas, eggs, yogurt, fish, chicken, groundnuts and egusi all count. If you eat plant-based, mix beans with grains through the day and ask your provider about B12, iron and DHA.", { foods: ["lentils", "egusi", "black-eyed-peas"], nutrients: ["Protein"] }),
  T("dha", ["omega", "dha", "brain development"], "DHA, an omega-3 fat, helps build your baby's brain and eyes. The easiest food sources are salmon, sardines and other low-mercury fish 2 to 3 times a week. Eggs have a little. If you don't eat fish, ask your provider whether an algae-based DHA makes sense.", { foods: ["salmon"], nutrients: ["Omega-3"] }),
  T("choline", ["choline"], "Choline supports your baby's brain and memory, and you need about 450 mg a day. Eggs are the star (about 150 mg each), along with chicken, fish, beans and yogurt. Many prenatal vitamins have little or none.", { nutrients: ["Choline"] }),
  T("vitd", ["vitamin d", "sunlight", "sun"], "Vitamin D helps your body use calcium. It's hard to get from food alone, and people with darker skin often make less from sunlight. Fortified milk, eggs, salmon and sardines help. Your provider can check your level and tell you if you need more."),
  T("water", ["water", "hydrat", "thirsty", "dehydrat", "fluids"], "Aim for about 8 to 12 cups of fluid a day, more when it's hot or you're active. Water, milk, soups and fruit all count. Pale yellow urine is a good sign you're getting enough.", { nutrients: ["Hydration"] }),
  T("weight", ["weight", "gain", "pounds", "kg", "fat", "too big"], "Healthy weight gain depends on where you started, usually somewhere between 15 and 35 pounds over the whole pregnancy. Your provider tracks this with you. You don't need to eat for two: in the second trimester you need only about 340 extra calories a day, roughly a bowl of beans and rice."),
  T("gdm", ["diabetes", "glucose", "sugar test", "blood sugar", "gestational"], "If you're doing glucose screening or managing blood sugar, the food basics are: pair carbs with protein and fiber, keep portions of rice, ugali and fufu moderate, choose beans and whole grains often, and spread food across 3 meals and 2 to 3 snacks. Your care team or a dietitian will set your specific targets.", { foods: ["black-eyed-peas", "lentils"], questions: ["Can I see a dietitian about my blood sugar?"] }),
  T("snacks", ["snack", "hungry", "between meals", "midnight"], "Good snacks pair protein or fat with fiber so they keep you full: groundnuts with fruit, a boiled egg and crackers, yogurt with oats, roasted chickpeas, or plantain with beans. Keep a few ready for when hunger hits fast.", { foods: ["greek-yogurt", "plantain"] }),
  T("breakfast", ["breakfast", "morning meal"], "A strong breakfast mixes protein, fiber and something fresh: eggs with toast and avocado, oats or koko with groundnuts and milk, yogurt with fruit, or leftover waakye. If mornings are queasy, start small and add more mid-morning.", { foods: ["waakye", "greek-yogurt", "avocado"] }),
  T("sleep", ["sleep", "insomnia", "can't sleep", "cant sleep", "awake at night", "tired at night"], "Pregnancy sleep is hard. From about 28 weeks, sleeping on your side is recommended (if you wake up on your back, just roll over, no need to worry). A pillow between your knees helps, as does an earlier, lighter dinner (less heartburn) and fewer fluids right before bed. A small snack with protein, like yogurt or groundnuts, can stop middle-of-the-night hunger.", { note: "Loud snoring, gasping, or feeling hopeless and unable to sleep even when you can are worth telling your provider." }),
  T("exercise", ["exercise", "workout", "walk", "walking", "gym", "yoga", "run", "running", "active", "dance"], "Most pregnant people can aim for about 150 minutes a week of moderate activity, like brisk walking, dancing, swimming or prenatal yoga, if your provider hasn't said otherwise. You should be able to talk while you move. Skip contact sports, and stop if you feel dizzy, have pain or bleeding."),
  T("cramps", ["leg cramp", "charley", "cramp in my leg"], "Leg cramps are common later in pregnancy, especially at night. Stretching your calves before bed, staying hydrated and moving during the day can help. Foods with magnesium and potassium, like beans, greens, avocado and plantain, are good to include.", { note: "A painful, swollen, warm or red leg (especially one side) needs a call to your provider today.", foods: ["avocado", "plantain"] }),
  T("swelling", ["swollen feet", "swollen", "swelling", "swollen ankles", "edema", "puffy"], "Some swelling in the feet and ankles is normal, especially at the end of the day. Putting your feet up, walking, staying hydrated and going easy on very salty foods (stock cubes, processed meats) can help.", { note: "Sudden swelling of your face or hands, or swelling with a headache or vision changes, needs a call to your provider right away." }),
  T("teas", ["herbal", "tea", "teas", "ginger tea", "hibiscus", "sobolo", "bissap", "moringa", "bitter leaf", "herbs", "traditional medicine"], "Many traditional herbs haven't been studied in pregnancy, so it's worth checking each one with your provider. Ginger tea in normal food amounts is generally considered okay and can help nausea. Please ask before using concentrated herbs, bitters or remedies.", { questions: ["Are the herbs or teas I use safe during pregnancy?"] }),
  T("spicy", ["spicy", "pepper", "hot sauce", "shito", "pepper soup"], "Spicy food is safe for your baby. The only issue is comfort: it can make heartburn worse. If shito or pepper soup sits well with you, enjoy it."),
  T("peanuts", ["peanut", "groundnut", "nuts", "allergen", "allergy"], "Unless you're allergic, there's no need to avoid peanuts or other common allergens in pregnancy or while breastfeeding. Groundnuts are a great snack with protein and healthy fats."),
  T("fasting", ["fast", "fasting", "ramadan", "lent", "skipping meals"], "Many people fast for faith, and it's a personal decision to make with your provider. If you fast, eat a filling pre-dawn meal with protein and slow carbs, drink plenty between sunset and sunrise, and break the fast if you feel dizzy, faint or notice less baby movement."),
  T("dates", ["dates", "labor prep", "induce", "start labor", "pineapple"], "Some small studies suggest eating about 6 dates a day in the last 4 weeks may help with labor, though the evidence is limited. They're a nutritious snack either way. Pineapple and spicy food won't start labor."),
  T("breastfeeding", ["breastfeed", "nursing", "milk supply", "lactat", "pump"], "While breastfeeding you need a bit more food and fluid than in pregnancy: about 450 to 500 extra calories a day and a glass of water each time you nurse. Keep up protein, iron-rich foods and DHA. Many cultures have galactagogue foods like oats and soups; they're nourishing, though the best way to build supply is frequent feeding.", { nutrients: ["Protein", "Omega-3"], note: "A lactation consultant or WIC peer counselor can help with supply or latch. See Support Near You." }),
  T("postpartum", ["after birth", "postpartum", "recovery", "c-section", "fourth trimester", "confinement"], "Recovery food can be simple and warm: soups, stews, beans, greens, eggs and fish to rebuild iron and protein. Many traditions, like light soup and pepper soup after birth, are wonderful. Rest, fluids and fiber matter too.", { foods: ["egusi", "black-eyed-peas", "callaloo"], nutrients: ["Iron", "Protein"] }),
  T("babyfood", ["solids", "baby food", "weaning", "first foods", "puree", "baby eat"], "Most babies are ready for solids around 6 months, when they can sit with support and show interest. Iron-rich first foods are best: mashed beans, egg, fish, meat, or fortified cereal, alongside soft vegetables and fruit. Your family's foods, mashed and unsalted, are perfect.", { note: "Avoid honey before age 1, and whole nuts or hard round foods that are choking risks." }),
  T("formula", ["formula", "bottle"], "Formula is a healthy way to feed your baby, alone or alongside breastfeeding. Follow the mixing directions exactly, never water it down, and use safe water. WIC can help cover formula if you qualify."),
  T("money", ["cheap", "save money", "expensive", "wic", "snap", "ebt", "food stamps"], "Nourishing food doesn't have to cost a lot: dried or canned beans, eggs, frozen greens, rice, oats, sweet potatoes, plantain and canned fish are all budget heroes. WIC and SNAP can help too, and Support Near You shows stores that take EBT near your ZIP.", { foods: ["black-eyed-peas", "sweet-potato"], actions: ["Create a grocery list"] }),
  T("meal-prep", ["meal prep", "batch", "freeze", "leftover", "prep ahead"], "Batch-cooking on a good day saves tired evenings: a big pot of beans or stew, rice, and roasted sweet potatoes keep 3 to 4 days in the fridge and freeze well. Reheat leftovers until steaming hot.", { actions: ["Build a meal", "Create a grocery list"] }),
  T("anxiety", ["anxious", "worried", "nervous", "stress", "scared", "overwhelmed"], "It makes so much sense to feel that way. Pregnancy brings a lot. Some things that help: regular meals (low blood sugar can make anxiety worse), a short walk, talking to someone you trust, and The Village. If worry is sticking around or getting in the way, try the 2-minute mood check and tell your provider. You can also call or text 1-833-TLC-MAMA any time."),
  T("baby-growth", ["baby size", "how big", "baby growing", "fruit size", "development"], "Your baby is growing fast right now. In the second trimester they're building bones, muscles and fat, and can hear your voice. Iron, protein, calcium and DHA from your meals help with all of it.", { nutrients: ["Iron", "Protein", "Calcium"] }),
  T("travel", ["travel", "flight", "fly", "trip", "road trip"], "Travel is usually fine through about 36 weeks if your pregnancy is healthy. Pack snacks and water, walk or stretch every 1 to 2 hours, and check your airline's rules. Ask your provider before a long trip, and be careful with food and water safety abroad."),
];

const SMALLTALK = [
  [/^(hi|hello|hey|good (morning|afternoon|evening)|yo|hola|akwaaba)\b/, (p) => `Hi ${p.name}! How are you feeling today? You can ask me anything, from what to eat tonight to how to handle heartburn.`],
  [/\b(thank|thanks|thx|appreciate)\b/, () => "You're so welcome. I'm here whenever you need me."],
  [/(who are you|what are you|what can you do|what do you do|are you (a )?(bot|ai|real|human))/, () => "I'm Afya, Amara's nutrition companion. I help with food, cravings, budget meals, symptoms that food can ease, and getting ready for your visits, always starting from the foods you already love. I'm an AI, not a clinician, so I'll point you to your care team for anything medical."],
  [/(how are you|how's it going|how are things)/, (p) => `I'm doing well, thank you for asking! More importantly, how are you feeling at ${stageLabel(p).toLowerCase()}?`],
  [/\b(bye|goodnight|good night|see you|later)\b/, () => "Take care of yourself. I'll be right here when you need me."],
  [/\b(lol|haha|funny|joke)\b/, () => "Here's one: why did the plantain go to the party? Because it was ripe for fun. Okay, I'll stick to nutrition. 🌿"],
];

const OFFTOPIC = /(weather|capital of|who won|history|translate|sports|score|game|movie|song|lyrics|stock|bitcoin|crypto|election|president|homework|math|code|program|recipe for cocktail)/;

const words = (t) => t.toLowerCase().replace(/[^a-z0-9' ]/g, " ");
const esc = (k) => k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
// Short keys must match a whole word ("tea" shouldn't match "steak"); longer keys can match a word start ("constipat").
const hit = (t, k) => new RegExp(`\\b${esc(k)}${k.length <= 4 ? "\\b" : ""}`).test(t);

export function knowledgeReply(raw, p) {
  const t = words(raw).trim();
  for (const [re, fn] of SMALLTALK) if (re.test(t) && t.split(" ").length <= 8) return { text: fn(p) };
  let best = null, score = 0;
  for (const topic of TOPICS) {
    const s = topic.keys.reduce((n, k) => n + (hit(t, k) ? k.length : 0), 0);
    if (s > score) { best = topic; score = s; }
  }
  if (best) {
    const { text, foods, nutrients, note, questions, actions } = best;
    return { text, foods, nutrients, note, questions, actions };
  }
  if (OFFTOPIC.test(t)) {
    return { text: `That one's outside what I know best, ${p.name}. I'm built for food, pregnancy, postpartum and everyday wellbeing. Anything on your mind there?`, ask: "I can also…", actions: ["Find foods I already eat", "Build a meal"] };
  }
  return null;
}
